spring.application.name=ecowatch
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.oixbpmejlujppgfqwmdl
spring.datasource.password=!ecowatch@123

spring.jpa.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update